default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: itextpdf_sample_development

test:
  <<: *default
  database: itextpdf_sample_test
  port: 5432
